version: '3.8'

services:
  app:
    build:
      context: ./tugas-manager
    container_name: laravel-app
    ports:
      - "8000:8000"
    volumes:
      - ./tugas-manager:/var/www
    depends_on:
      - mysql
    networks:
      - laravel

  mysql:
    image: mysql:8
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_DATABASE: tugas
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - laravel

volumes:
  db_data:

networks:
  laravel:
